version: '3.8'

services:
  db:
    image: expertdb
    build: ./expertDB
    restart: always
    environment:
      # To be replaced once ready for deployment
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: db_container